sudo: false
language: node_js
node_js:
  - '10'
  - '11'
cache:
  directories:
  - node_modules
before_script: 
  - sudo redis-server /etc/redis/redis.conf --port 6380 --requirepass 'secret'
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
