const GET_PEOPLE_REQUEST = 'start-wars-GET_PEOPLE_REQUEST';
const GET_PEOPLE_SUCCESS = 'start-wars-GET_PEOPLE_SUCCESS';
const GET_PEOPLE_FAILURE = 'start-wars-GET_PEOPLE_FAILURE';
const GET_EACH_PERSON_FILED_REQUEST = 'start-wars-GET_EACH_PERSON_FILED_REQUEST';
const GET_EACH_PERSON_FILED_SUCCESS = 'start-wars-GET_EACH_PERSON_FILED_SUCCESS';
const GET_EACH_PERSON_FILED_FAILURE = 'start-wars-GET_EACH_PERSON_FILED_FAILURE';
const OPEN_MODAL_REQUEST = 'start-wars-OPEN_MODAL_REQUEST';
const OPEN_MODAL_SUCCESS = 'start-wars-OPEN_MODAL_SUCCESS';
const OPEN_MODAL_FAILURE = 'start-wars-OPEN_MODAL_FAILURE';
const CLOSE_MODAL_REQUEST = 'start-wars-CLOSE_MODAL_REQUEST';
const CLOSE_MODAL_SUCCESS = 'start-wars-CLOSE_MODAL_SUCCESS';
const CLOSE_MODAL_FAILURE = 'start-wars-CLOSE_MODAL_FAILURE';

export {
  GET_PEOPLE_REQUEST,
  GET_PEOPLE_SUCCESS,
  GET_PEOPLE_FAILURE,
  GET_EACH_PERSON_FILED_REQUEST,
  GET_EACH_PERSON_FILED_SUCCESS,
  GET_EACH_PERSON_FILED_FAILURE,
  OPEN_MODAL_REQUEST,
  OPEN_MODAL_SUCCESS,
  OPEN_MODAL_FAILURE,
  CLOSE_MODAL_REQUEST,
  CLOSE_MODAL_SUCCESS,
  CLOSE_MODAL_FAILURE,

};
